### ISSUE TITLE
Errors with mi 9

### ISSUE THREAD

**Issue by ale8530** [XiaomiFirmwareUpdater/miui_arb_checker#3]
Problem with mi9 cepheus

`ale8530@vmi81507:~/miui.it/tools/downloaded_roms$ python3 miui_arb_checker.py miui_CEPHEUS_9.5.16_52cdcb354a_9.0.zip
Checking ARB from Recovery ROM
xbl file extracted successfully.
Traceback (most recent call last):
  File "miui_arb_checker.py", line 151, in <module>
    main()
  File "miui_arb_checker.py", line 134, in main
    check_xbl(file_type)
  File "miui_arb_checker.py", line 95, in check_xbl
    get_arb_number(xbl)
  File "miui_arb_checker.py", line 76, in get_arb_number
    if i != '0000000000000000'][0]
IndexError: list index out of range`

**Comment by yshalsager** [comment]
Fixed https://github.com/XiaomiFirmwareUpdater/miui_arb_checker/commit/ef34da8725f229b81d72fe48a4a02abc2aa97c4f
Thanks for reporting!
